# ----------------------------------------------------------
#  SOFTWARE INFO
# ----------------------------------------------------------
Title: 'GEN MOL'
Version: '2.0'


# ----------------------------------------------------------
#  DIRECTORIES
# ----------------------------------------------------------
Docked_Directory: 'Docked'
Output_Directory: 'Output'
Database_Directory: 'sqlite:///Database/atoms.sqlite'


# ----------------------------------------------------------
#  DATABASE
# ----------------------------------------------------------
Database_Create: False


# ----------------------------------------------------------
#  GRID
# ----------------------------------------------------------
Grid_Size: 2 # Anstroms

Score_Threshold: -5.0 # Gibbs Free Energy

Receptor:
  Origin:
    X: 18
    Y: -35
    Z: -18
  Box_Size:
    X: 25
    Y: 25
    Z: 25